export interface Product {
  id: number,
  name: string,
  nameRoute: string,
  categorie_tente: boolean,
  categorie_dtente: boolean,
  garantie: string,
  periode_essai: string,
  alaUne: boolean,
  video: string,
  titrevideo:string,
  image: string,
  image_routeur : string,
  image_screen :[
    id1: string,
    id2: string,
    id3: string,
    id4: string,
    id5: string
  ];
  price_sell: number,
  price_promo: number,
  price_rent_day: number,
  price_metropole: number,
  amazon: string,
  description: string,
  description_long: string,
  stars: number,
  avis_web: string,
  stock: number,
  poids: number,
}

export const products: Product[] = [
    {
    id: 1,
    name: 'Tente de toit: L=210 l=125 H=95',
    nameRoute: 'Tente-de-toit-de-voiture-125',
    categorie_tente: true,
    categorie_dtente: true,
    garantie:'Constructeur 1 an',
    periode_essai: '1 semaine',
    video: 'ZFj4WUZiBBc',
    titrevideo:'',
    alaUne: false,
    image :'../assets/images/product/tentedetoit/hard-reunion/tente-de-toit-fibre-de-verre-hermitage-29-06-2023.webp',
    image_routeur:'../assets/images/product/tentedetoit/H7fe85f62303e4ebd80c1c29fc6736256p.jpg_720x720q50.webp',
    image_screen :[
      '../assets/images/product/tentedetoit/hard-reunion/tente-de-toit-fibre-de-verre-hermitage-29-06-2023.webp',
      '../assets/images/product/tentedetoit/hard-reunion/tente-de-toit-fibre-de-verre-01-webp.webp',
      '../assets/images/product/tentedetoit/hard-reunion/tente-de-toit-fibre-de-verre-02-webp.webp',
      '../assets/images/product/tentedetoit/hard-reunion/tente-de-toit-fibre-de-verre-03-webp.webp',
      '',
    ],
    price_sell: 2350,
    price_promo: 2250,
    price_rent_day: 80,
    price_metropole: 0,
    amazon: '',
    description: 'Tente de L:210 l:125 pour 2 places - La tente de toit Fibre de Verre et alu est montée en quelques minutes,Norme Iso 9001',
    description_long : '<p><h3><b>Description</b></h3></p><p>La tente de toit à coque dure offre une nouvelle façon de voir le camping et les vacances d\'aventure en 4x4. Avec un espace intérieur plus grand, elle offre un espace de couchage pour deux adultes et un enfant. La tente à toit rigide PLAYDO a deux portes et deux fenêtres, ce qui crée une excellente ventilation transversale permettant à l\'air de circuler librement dans toute la tente. Ouvrez et fermez en quelques secondes avec le système de support hydraulique unique. Toutes les tentes de toit s\'adaptent au toit de la plupart des véhicules et peuvent être retirées et stockées lorsqu\'elles ne sont pas nécessaires et sont couvertes par une garantie de 1 an sur le tissu, la coque et le mécanisme.</p><p><b>Caractéristiques</b></p><ul><li>1. Élastiques pour le pliage interne du tissu</li><li>2. Structure stable, imperméable et coupe-vent</li><li>3. Échelle en alliage réglable et sac porte-échelle</li><li>4. Recommandé pour 2 adultes</li></ul>',
    stars: 5,
    avis_web:"",
    stock: 3,
    poids: 75
  },
  {
    id: 2,
    name: 'Tente de toit: L=210 l=145 H=95',
    nameRoute: 'Tente-de-toit-de-voiture-145',
    categorie_tente: true,
    categorie_dtente: true,
    garantie:'Constructeur 1 an',
    periode_essai: '1 semaine',
    video: 'ZFj4WUZiBBc',
    titrevideo:'',
    alaUne: false,
    image :'../assets/images/product/tentedetoit/hard-reunion/tente-de-toit-fibre-de-verre-01-webp.webp',
    image_routeur:'../assets/images/product/tentedetoit/H7fe85f62303e4ebd80c1c29fc6736256p.jpg_720x720q50.webp',
    image_screen :[
      '../assets/images/product/tentedetoit/hard-reunion/tente-de-toit-fibre-de-verre-hermitage-29-06-2023',
      '../assets/images/product/tentedetoit/hard-reunion/tente-de-toit-fibre-de-verre-01-webp.webp',
      '../assets/images/product/tentedetoit/hard-reunion/tente-de-toit-fibre-de-verre-02-webp.webp',
      '../assets/images/product/tentedetoit/hard-reunion/tente-de-toit-fibre-de-verre-03-webp.webp',
      '',
    ],
    price_sell: 2450,
    price_promo: 2350,
    price_rent_day: 90,
    price_metropole: 0,
    amazon: '',
    description: 'Tente de L:210 l:145 pour 3 places - La tente de toit Fibre de Verre et alu est montée en quelques minutes,Norme Iso 9001',
    description_long : '<p><h3><b>Description</b></h3></p><p>La tente de toit à coque dure offre une nouvelle façon de voir le camping et les vacances d\'aventure en 4x4. Avec un espace intérieur plus grand, elle offre un espace de couchage pour deux adultes et un enfant. La tente à toit rigide PLAYDO a deux portes et deux fenêtres, ce qui crée une excellente ventilation transversale permettant à l\'air de circuler librement dans toute la tente. Ouvrez et fermez en quelques secondes avec le système de support hydraulique unique. Toutes les tentes de toit s\'adaptent au toit de la plupart des véhicules et peuvent être retirées et stockées lorsqu\'elles ne sont pas nécessaires et sont couvertes par une garantie de 1 an sur le tissu, la coque et le mécanisme.</p><p><b>Caractéristiques</b></p><ul><li>1. Élastiques pour le pliage interne du tissu</li><li>2. Structure stable, imperméable et coupe-vent</li><li>3. Échelle en alliage réglable et sac porte-échelle</li><li>4. Recommandé pour 2 adultes + 1 enfant</li></ul>',
    stars: 5,
    avis_web:"",
    stock: 3,
    poids: 80
  },
  {
    id: 2,
    name: 'Tente de toit: L=240 l=140 H=95 ',
    nameRoute: 'Tente-de-toit-de-voiture-soft',
    categorie_tente: true,
    categorie_dtente: true,
    garantie:'Constructeur 1 an',
    periode_essai: '1 semaine',
    video: 'ZFj4WUZiBBc',
    titrevideo:'',
    alaUne: false,
    image :'../assets/images/product/tentedetoit/H9074a4ed173f4d8f913b94f4473c445fO.jpg_720x720q50.webp',
    image_routeur:'../assets/images/product/tentedetoit/H9074a4ed173f4d8f913b94f4473c445fO.jpg_720x720q50.webp',
    image_screen :[
      '../assets/images/product/tentedetoit/soft/tente-de-toit-soft-A.webp',
      '../assets/images/product/tentedetoit/soft/tente-de-toit-soft-B.webp',
      '../assets/images/product/tentedetoit/soft/tente-de-toit-soft-C.webp',
      '../assets/images/product/tentedetoit/soft/tente-de-toit-soft-D.webp',
      '../assets/images/product/tentedetoit/soft/tente-de-toit-soft-E.webp',
    ],
    price_sell: 1850,
    price_promo: 1790,
    price_rent_day: 75,
    price_metropole: 1750,
    amazon: '',
    description: 'Idéal Famille : 4 personnes - La tente de toit Soft Shell 4x4 est montée en quelques minutes,Norme Iso 9001',
    description_long : '<p><h3><b>Description</b></h3></p><p>La tente de toit Soft Shell 4x4 est montée en quelques minutes, pour que vous puissiez vous détendre et profiter du plein air. Fabriquée à partir de tissu respirant poly/coton durable de haute qualité, votre tente de toit étanche à la moisissure et à l\'eau s\'adapte parfaitement au toit de votre 4x4. Une échelle rétractable en aluminium robuste permet un accès facile. Les matelas sont livrés avec un matelas en mousse haute densité de 65 mm avec une housse amovible. Avec fenêtres et portes entièrement grillagées. anti-poussière et anti-insectes.</p><p><b>Caractéristiques</b</p><ul><li>1. 280gTissu à double couture (40% plus lourd que les modèles standard)</li><li>2. Tapis anti-condensation (1/2) sous le matelas</li><li>3. Cadre interne robuste de 3/4 "entièrement enveloppé</li><li>4. Charnières à 3 boulons robustes et construction de base en aluminium soudé</li><li>5. Poches internes extra-larges, points d\'ancrage pour engrenages et sangles de literie</li><li>6. Annexe entièrement fermée avec le même matériau robuste utilisé pour la toile de tente</li></ul>',
    stars: 5,
    avis_web:'',
    stock: 1,
    poids: 75
  },
  {
    id: 3,
    name: 'Tente Qaou V5 pack 3 en 1',
    nameRoute: 'Tente-Qaou-V5-pack-3en1 ',
    categorie_tente: true,
    categorie_dtente: false,
    garantie:'2 ans',
    periode_essai: '3 semaines',
    video: 'MaX89pkMqm0',
    titrevideo:'&#128578; | Adventure V5 - 6 en 1',
    alaUne: false,
    image :'../assets/images/product/qaou/tente-v5-Qaou-tente-3-en-1-300x300.webp',
    image_routeur:'../assets/images/product/qaou/tente-v5-qaou-tente-3-en-1-2500x2500.webp',
    image_screen :[
      '../assets/images/product/qaou/qaou-adventure-v5-3-en-1/Qaou-v5-3-en1-A.webp',
      '../assets/images/product/qaou/qaou-adventure-v5-3-en-1/Qaou-v5-3-en1-B.webp',
      '../assets/images/product/qaou/qaou-adventure-v5-3-en-1/Qaou-v5-3-en1-C.webp',
      '../assets/images/product/qaou/qaou-adventure-v5-3-en-1/Qaou-v5-3-en1-D.webp',
      '../assets/images/product/qaou/qaou-adventure-v5-3-en-1/Qaou-v5-3-en1-E.webp'
    ],
    price_sell: 179.00,
    price_promo: 159,
    price_rent_day: 22,
    price_metropole: 213,
    amazon: '',
    description: 'Le toit de la tente se transforme en hamac ou en tarp vous pourrez donc moduler l’utilisation de votre Qaou en fonction de vos besoins',
    description_long : '<p><b>La Qaou V5 est la dernière version créer par Qaou. Elle bénéficie des 5 années de recherches et développement pour améliorer les performances de nos tentes</b>.<\p><p>Sous tente: Polyamide  et polyester PU 4000 mm<\p><p>Arceaux: Aluminium 8,5 mm<\p><p>1 Double toit modulable: Polyamide 70 D ripstop PU 2000 mm (1 seul double toit / Hamac est fourni dans ce pack)<\p><p>Ce pack vous offre les fonctions suivantes:<\p><p>Tente / Hamac / Abri<\p><p><i>Peut être complété par la suite avec un hamac supplémentaire et un kit de fixation pour avoir l’équivalent d’un pack Adventure. (Tente  / Hamac  / Abri / Tarp)<\i><\p><p>Tente 2 Personnes. Qaou est conçue pour s’adapter à différentes situations, partout où vous irez Qaou s’adaptera !<\p><p>Le toit de la tente se transforme en hamac ou en tarp vous pourrez donc moduler l\’utilisation de votre Qaou en fonction de vos besoins<\p>',
    stars: 5,
    avis_web:"https://www.experience-outdoor.com/test-de-la-tente-qaou-v4/",
    stock: 3,
    poids: 2.4
  },
  {
    id: 4,
    name: 'Adventure V5 - 6 en 1',
    nameRoute: 'Tente-Qaou-Adventure-V5-pack-6-en-1',
    categorie_tente: true,
    categorie_dtente: false,
    garantie:'2 ans',
    periode_essai: '3 semaines',
    alaUne: true,
    video: 'MaX89pkMqm0',
    titrevideo:'&#128578; | Adventure V5 - 6 en 1',
    image :'../assets/images/product/qaou/adventure-V5- Qaou- Reunion-300x300.webp',
    image_routeur:'../assets/images/product/qaou/adventure-v5-Qaou-reunion-2400-2400.webp',
    image_screen :[
      '../assets/images/product/qaou/qaou-adventure-v5-6-en-1/Qaou-V5-6-en1-A.webp',
      '../assets/images/product/qaou/qaou-adventure-v5-6-en-1/Qaou-V5-6-en1-B.webp',
      '../assets/images/product/qaou/qaou-adventure-v5-6-en-1/Qaou-V5-6-en1-C.webp',
      '../assets/images/product/qaou/qaou-adventure-v5-6-en-1/Qaou-V5-6-en1-D.webp',
      '../assets/images/product/qaou/qaou-adventure-v5-6-en-1/Qaou-V5-6-en1-E.webp',
    ],
    price_sell: 239.00,
    price_promo: 219,
    price_rent_day: 25,
    price_metropole: 239,
    amazon: '',
    description: 'Ce pack vous offre les fonctions suivantes: Tente /Tente + auvent / Hamac / Hamac + tarp / Abri / Tarp . Les piquets et l armature en Aluminium No plastique',
    description_long : '<b>La Qaou Adventure V5 est la dernière version créer par Qaou. Elle bénéficie des 5 années de recherches et développement pour améliorer les performances de nos tentes.  </b> <p>Sous tente: Polyamide  et polyester PU 4000 mm</p><p>Arceaux: Aluminium 8,5 mm</p><p>Double toit modulable: Polyamide 70 D ripstop PU 2000 mm</p><p>Ce pack vous offre les fonctions suivantes: Tente /Tente + auvent / Hamac / Hamac + tarp / Abri / Tarp</p><p>Tente 2 Personnes. Qaou est conçue pour s adapter à différentes situations, partout où vous irez Qaou s’adaptera !</p><p>Le toit de la tente se transforme en hamac ou en tarp vous pourrez donc moduler l’utilisation de votre Qaou en fonction de vos besoins</p>   <p>2 hamacs sont livrés dans le pack ce qui vous permet de multiple configurations différentes</p>',
    stars: 5,
    avis_web:"https://www.experience-outdoor.com/test-de-la-tente-qaou-v4/",
    stock: 3,
    poids: 3.3
  },
  {
    id: 4,
    name: 'Bâton de marche ergonomique',
    nameRoute: 'Paire-de-bâtons-de-marche-ergonomiques',
    categorie_tente: true,
    categorie_dtente: true,
    garantie:'2 ans',
    periode_essai: '3 semaines',
    alaUne: true,
    video: '',
    titrevideo:'',
    image :'../assets/images/product/qaou/Baton-de-marche-plie-600x600-webp.webp',
    image_routeur:'../assets/images/product/qaou/Baton-de-marche-plie-600x600-webp.webp',
    image_screen :[
      '../assets/images/product/qaou/Baton-de-marche-plie-600x600-webp.webp',
      '../assets/images/product/qaou/baton-de-marche-ccessoire.webp',
      '../assets/images/product/qaou/Baton-de-marche.jpeg',
      '',
      '',
    ],
    price_sell: 59.00,
    price_promo: 35,
    price_rent_day: 5,
    price_metropole: 59,
    amazon: '',
    description: 'Bâtons de marche Haut de gamme.Prix constaté Ile de la Réunion sur même qualité : 70 euros..',
    description_long : '<b>Bâtons de marche Qaou ergonomiques, réglage télescopique très utile pour aider lors d’une marche mais également pour augmenter les possibilités de la tente Qaou.</b> <p>Poids : 300 gr un bâton</p><p>Fournit avec / Une housse de rangement, 2 pointes métal de rechanges, 2 rondelles trekking, 2 rondelles touring, 2 type d’embouts de protections en caoutchouc lors de passages sur asphalte et sur chemin sec.</p><p>Système de verrouillage par clip en aluminium (+ molette de force de serrage sur chaque points de serrage)</p>',
    stars: 5,
    avis_web:"https://www.experience-outdoor.com/test-de-la-tente-qaou-v4/",
    stock: 3,
    poids: 0.3
  },
  
  {
    id: 7,
    name: 'Hamac / double toit vert',
    nameRoute: 'Qaou-Hamac-double-toi-vert',
    categorie_tente: true,
    categorie_dtente: false,
    garantie:'2 ans',
    periode_essai: '3 semaines',
    alaUne: false,
    video: 'sIVkaVMPMKk',
    titrevideo:'&#128578; | Hamac Qaou Double toit',
    image :'../assets/images/product/qaou/Qaou-hamacV4-1-300x300.webp',
    image_routeur:'../assets/images/product/qaou/Qaou-hamacV4-1-2400x2400.webp',
    image_screen :[
      '../assets/images/product/qaou/Qaou-hamacV4-1-2400x2400.webp',
      '',
      '',
      '',
      ''
    ],
    price_sell: 49.00,
    price_promo: 0,
    price_rent_day: 10,
    price_metropole: 49,
    amazon: '',
    description: 'Fonctions : Toit pour la sous tente + Auvent à la tente + Grand tarp avec un autre hamac Qaou (Mousqueton: non fournis) - toile en Polyamide 70D', description_long : '<p<i>Le hamac multifonction Qaou est une toile en Polyamide verte qui peut être suspendue entre deux points d’ancrage.</i><\p><p>-Livré avec les boucles pour former le hamac</p><p>-Livré avec son sac de rangement.</p><p>FONCTIONS /</p><p>-Toit pour la sous tente QAOU</p><p>-Auvent à la tente</p><p>-Grand tarp avec un autre hamac Qaou</p><p><i>Les mousquetons et les sangles nécessaires pour suspendre le hamac ne sont pas fournis dans ce produit.</i></p>',
    stars: 5,
    avis_web:"https://www.experience-outdoor.com/test-de-la-tente-qaou-v4/",
    stock: 5,
    poids: 0.6
  },
  {
    id: 8,
    name: 'Kit fixation hamac 3m',
    nameRoute: 'Qaou-Kit-fixation-hamac-3m',
    categorie_tente: true,
    categorie_dtente: false,
    garantie:'2 ans',
    periode_essai: '3 semaines',
    alaUne: false,
    video: '',
    titrevideo:'',
    image :'../assets/images/product/qaou/Qaou-Sangle-3m-4-300x300.webp',
    image_routeur:'../assets/images/product/qaou/Qaou-Sangle-3m-4-600x600.webp',
    image_screen :[
      '../assets/images/product/qaou/Qaou-Sangle-3m-4-600x600.webp',
      '',
      '',
      '',
      ''
    ],
    price_sell: 22,
    price_promo: 0,
    price_rent_day: 2,
    price_metropole: 23,
    amazon: '',
    description: 'Les sangles de fixation et les mousquetons permettent d installer le hamac Qaou sur deux points fixes, 2 sangles de 3m - 150 Kg / sangle',
    description_long : '<p>-2 sangles de 3m de résistance de 150 Kg par sangle.</p><p>-Chaque sangle dispose de 9 boucles d’attache.</p><p>-2 mousquetons</p><p>-Livré dans son sac de rangement.</p>',
    stars: 5,
    avis_web:"https://www.experience-outdoor.com/test-de-la-tente-qaou-v4/",
    stock: 2,
    poids: 0.42
  },
  {
    id: 9,
    name: 'Matelas Randonnée multifonctionel',
    nameRoute: 'Qaou-Matelas-Randonnée',
    categorie_tente: true,
    categorie_dtente: false,
    garantie:'2 ans',
    periode_essai: '3 semaines',
    alaUne: false,
    video: '',
    titrevideo:'',
    image :'../assets/images/product/qaou/Qaou-Sleeping-pad2-300x300.webp',
    image_routeur:'../assets/images/product/qaou/Qaou-Sleeping-pad2-2400x2400.webp',
    image_screen :[
      '../assets/images/product/qaou/Qaou-Sleeping-pad2-2400x2400.webp',
      '',
      '',
      '',
      ''
    ],
    price_sell: 61,
    price_promo: 0,
    price_rent_day: 8,
    price_metropole: 61,
    amazon: '',
    description: 'Matelas gonflable ultra compact qui se gonfle grâce à son sac de rangement!.Il s’adapte aussi bien au hamac qu’à la tente : 1 pers',
    description_long : '<h1>Le sleeping pad Qaou est un matelas gonflable orange ultra compact qui se gonfle grâce à son sac de rangement.</h1><p>Épaisseur / 5 cm</p><p>Longueur / 210 cm</p><p>Largeur / 60 cm</p><p>Poids / 550 gr sans son sac de rangement / 650 gr avec son sac de rangement</p><p>Waterproof – R Value 1,3</p><p>Conçu pour une personne il s’adapte aussi bien au hamac qu’à la tente Qaou.</p>',
    stars: 5,
    avis_web:"https://www.experience-outdoor.com/test-de-la-tente-qaou-v4/",
    stock: 2,
    poids: 0.65
  },
  {
    
    id: 10,
    name: 'Couteau Suisse Huntsman Wood',
    nameRoute: 'Couteau-Suisse-Huntsman-Wood-victorinox',
    categorie_tente: true,
    categorie_dtente: false,
    garantie:'2 ans',
    periode_essai: '',
    alaUne: false,
    video: 'EmY9WEl4DDw',
    titrevideo:'Multples utilisations du Huntsman wood',
    image :'../assets/images/product/qaou/Qaou-victorinox-1-300x300.webp',
    image_routeur:'../assets/images/product/qaou/Qaou-victorinox-1-2400x2400.webp',
    image_screen :[
      '../assets/images/product/qaou/Qaou-victorinox-1-2400x2400.webp',
      '',
      '',
      '',
      ''
    ],
    price_sell: 49.95,
    price_promo: 0,
    price_rent_day: 2,
    price_metropole: 57,
    amazon: '',
    description: 'Couteau de poche de taille moyenne avec côtes en noyer : Collection spéciale Huntsman : 13 fonctions dont une paire de ciseaux',
    description_long : '<h1>Collection spéciale du célèbre couteau suisse Huntsman en bois de noyer avec marquage Qaou et Victorinox</h1><p>Aussi fonctionnel qu’élégant, le couteau suisse Huntsman Wood dissimule pas moins de 13 outils essentiels sous des côtes très fines en bois de noyer résistant et noble. </p><p> C’est ce même bois aux veinures naturelles qui donne à chacun des couteaux son caractère unique et artisanal et un toucher incomparable. </p><p> Mais n’allez pas croire pour autant qu’il s’agit d’un couteau délicat à manier avec précaution.</p><p>  Ce compagnon noble et léger est pensé pour le quotidien et pour chaque aventure susceptible de se présenter, que vous l’ayez dans la poche ou dans votre boîte à outils.',
    stars: 5,
    avis_web:"https://www.victorinox.com/fr/fr/Produits/Couteaux-suisses/Couteaux-de-poche-taille-moyenne/Huntsman-Wood/p/1.3711.63",
    stock: 2,
    poids: 0
  },
  {
    id: 11,
    name: 'Aiguiseur/Affuteur Sharpal 6en1',
    nameRoute: 'Aiguiseur/Affuteur-Sharpal-101N-6-en-1',
    categorie_tente: true,
    categorie_dtente: false,
    garantie:'',
    periode_essai: '',
    alaUne: false,
    video: '5YMamVDTOUs',
    titrevideo:'Aiguiseur multifonctions',
    image :'../assets/images/product/qaou/Qaou-aiguiseur-sharp-0-300x300.webp',
    image_routeur:'../assets/images/product/qaou/Qaou-aiguiseur-sharp-0-2400x2400.webp',
    image_screen :[
      '../assets/images/product/qaou/Qaou-aiguiseur-sharp-0-2400x2400.webp',
      '',
      '',
      '',
      ''
    ],
    price_sell: 13.96,
    price_promo: 0,
    price_rent_day: 2,
    price_metropole: 13.86,
    amazon: '',
    description: 'Aiguiseur de couteaux de poche 6 en 1 et outil de survie, avec allume-feu, sifflet et tige d affûtage en diamant, répare, restaure et affûte rapidement.',
    description_long : '<p>Cet outil permet d’aiguiser et d’affuter vos couteaux, scies, ou hameçons sur le terrain.</p><p> Léger (45g) et compact (9*4*1,5 cm) il tient dans une poche et permet de rattraper une lame qui a subi un choc facilement.</p><p>L’option sifflet peut s’avérer utile dans certaines situations, un plus qui est appréciable.</p><p> Au même titre que la pierre à feu, cet outil peut vous sauver de certaines situations, lorsqu’on a oublié son briquet pour le réchaud, par exemple.<p>',
    stars: 5,
    avis_web:"https://www.victorinox.com/fr/fr/Produits/Couteaux-suisses/Couteaux-de-poche-taille-moyenne/Huntsman-Wood/p/1.3711.63",
    stock: 2,
    poids: 0
  },
  {
    id: 12,
    name: 'Tour de cou multifonctionnel',
    nameRoute: 'Tour-de-cou-multifonction-original-Buff-Qaou',
    categorie_tente: true,
    categorie_dtente: false,
    garantie:'',
    periode_essai: '',
    alaUne: false,
    video: '3hKn6_adBMw',
    titrevideo:'Tour de cou buff multifonctions',
    image :'../assets/images/product/qaou/buffxqaou2-300x300.webp',
    image_routeur:'../assets/images/product/qaou/Buffxqaou2-2400x2400.webp',
    image_screen :[
      '../assets/images/product/qaou/Buffxqaou2-2400x2400.webp',
      '',
      '',
      '',
      ''
    ],
    price_sell: 16.96,
    price_promo: 0,
    price_rent_day: 2,
    price_metropole: 16.96,
    amazon: '',
    description: 'Confortable, extensible et doté d’une protection solaire, vous aurez une grande modularité d’utilisation: du pratique et de l’esthétique! ',
    description_long : '<p>Tour de cou multifonction Original Buff X Qaou conçu à partir de bouteilles plastiques recyclées.</p><p>Le nouveau multifonctionnel classique: Plus flexible, fibre recyclée, protection solaire et sans coutures.</p><p>Technologie Ultrastretch : Ajustement dans 4 directions pour une meilleure tenue et un confort optimal.</p><p>Profitez de la multifonctionnalité : choisissez comment le porter !</p> <p>Confortable, extensible et doté d’une protection solaire, avec notre tour de cou vous aurez une grande modularité d’utilisation: du pratique et de l’esthétique!  Ce produit multifonction est conçu pour une utilisation en toute saison et au cours de toutes vos aventures: trek, randonnée, cyclisme, moto…</p><p>Taille unique. Conçu pour adultes.</p><p>95% polyestère recyclé, 5% élasthanne</p>',
    stars: 5,
    avis_web:"https://www.victorinox.com/fr/fr/Produits/Couteaux-suisses/Couteaux-de-poche-taille-moyenne/Huntsman-Wood/p/1.3711.63",
    stock: 2,
    poids: 0
  },
  {
    id: 13,
    name: 'Trousse de Secours Qaou',
    nameRoute: 'Trousse-de-Secours-Qaou',
    categorie_tente: true,
    categorie_dtente: false,
    garantie:'',
    periode_essai: '',
    alaUne: false,
    video: '',
    titrevideo:'',
    image :'../assets/images/product/qaou/troussedesecours-300x300.webp',
    image_routeur:'../assets/images/product/qaou/troussedesecours-600x600.webp',
    image_screen :[
      '../assets/images/product/qaou/troussedesecours-600x600.webp',
      '',
      '',
      '',
      ''
    ],
    price_sell: 35,
    price_promo: 0,
    price_rent_day: 5,
    price_metropole: 35,
    amazon: '',
    description: '38 articles:Trousse de secours pour les pratiques Outdoor tel que la randonnée ou le bivouac. Fabriqué en France',
    description_long : '<p>Trousse de secours composée par l’équipe Qaou spécialement imaginée pour les pratiques Outdoor tel que la randonnée ou le bivouac,</p><p>elle est composée de :</p><p>-5 compresses stériles,</p><p>-3 compresses de Chlorhexidine (désinfection plaies légères)</p><p>-2 compresses Arnica ( choc /bleus)</p><p>-15 pansements</p><p>-1 bande</p><p>-1 paire de ciseaux</p><p>-2 épingles à nourrice</p><p>-1 couverture de survie</p><p>-1 pince à écharde</p><p>-3 comprimés de micropure</p><p>-1 pince à tique avec loupe</p><p>-1 bougie chauffe plat</p><p>-1 gel anti brûlure.</p><p>-1 kit de couture.</p><p>Le tout dans une trousse made in France dépliante pratique et compacte.</p>',
    stars: 5,
    avis_web:"https://www.victorinox.com/fr/fr/Produits/Couteaux-suisses/Couteaux-de-poche-taille-moyenne/Huntsman-Wood/p/1.3711.63",
    stock: 2,
    poids: 0.2
  },
  {
    id: 14,
    name: 'Porte-Bebe',
    nameRoute: 'Porte-Bebe',
    categorie_tente: false,
    categorie_dtente: true,
    garantie:'',
    periode_essai: '',
    alaUne: false,
    video: '',
    titrevideo:'',
    image :'../assets/images/product/decatlon/detentes.porte.bebe.webp',
    image_routeur:'../assets/images/product/decatlon/detentes.porte.bebe.webp',
    image_screen :[
      '../assets/images/product/decatlon/detentes.porte.bebe.webp',
      '',
      '',
      '',
      ''
    ],
    price_sell: 0,
    price_promo: 0,
    price_rent_day: 15,
    price_metropole: 0,
    amazon: '',
    description: 'Porte Bébé Deuter. Pour vos ballades et randos. Poids maximum 18 kg - Pare-soleil, siège ajustable et un dos respirant ',
    description_long : "à compléter",
    stars: 5,
    avis_web:"",
    stock: 1,
    poids: 0
  },
  {
    id: 15,
    name: 'Paddle avec gonfleur',
    nameRoute: 'Paddle-avec-gonfleur',
    categorie_tente: false,
    categorie_dtente: true,
    garantie:'',
    periode_essai: '',
    alaUne: false,
    video: 'OMx3W-0-5dM',
    titrevideo:'&#128578; | Vous fournissons un gonfleur électrique !',
    image :'../assets/images/product/decatlon/dentes.paddle.webp',
    image_routeur :'../assets/images/product/decatlon/dentes.paddle.webp',
    image_screen :[
      '../assets/images/product/decatlon/dentes.paddle.webp',
      '',
      '',
      '',
      ''
    ],
    price_sell: 0,
    price_promo: 0,
    price_rent_day: 25,
    price_metropole: 0,
    amazon: '',
    description: 'Paddle Itiwit avec gonfleur électrique.Très stable et facile, pour des gabarits supérieurs à 80 kg. Idéal pour l Hermitage ou Etang Salé',
    description_long : 'A compléter',
    stars: 5,
    avis_web:"",
    stock: 1,
    poids: 0
  },
  {
    id: 17,
    name: 'Pompe électrique-16psiA',
    nameRoute: 'Pompe électrique-16psiA',
    categorie_tente: false,
    categorie_dtente: true,
    garantie:'',
    periode_essai: '',
    alaUne: false,
    video: '',
    titrevideo:'',
    image :'../assets/images/product/flysurf/dtentes.pompe.electrique-16PSI-A.webp',
    image_routeur:'../assets/images/product/flysurf/dtentes.pompe.electrique-16PSI-A.webp',
    image_screen :[
      '../assets/images/product/flysurf/dtentes.pompe.electrique-16PSI-A.webp',
      '',
      '',
      '',
      ''
    ],
    price_sell: 0,
    price_promo: 0,
    price_rent_day: 6,
    price_metropole: 0,
    amazon: '',
    description: 'Livré complet avec 5 embouts, 2 tailles de joint, câble allume-cigare :SUP gonflable, kayaks, bateaux, matelas, etc',
    description_long : "Livré avec deux joints de taille différents pour les SUP gonflable, il ne faut pas hésiter à en retirer un et à alterner pour trouver celui qui s'adapte parfaitement !",
    stars: 5,
    avis_web:"",
    stock: 1,
    poids: 0
  },
  {
    id: 18,
    name: 'Pompe électrique-16psiB',
    nameRoute: 'Pompe électrique-16psiB',
    categorie_tente: false,
    categorie_dtente: true,
    garantie:'',
    periode_essai: '',
    alaUne: false,
    video: '',
    titrevideo:'',
    image :'../assets/images/product/flysurf/dtentes.pompe.electrique-16PSI-B.webp',
    image_routeur:'../assets/images/product/flysurf/dtentes.pompe.electrique-16PSI-B.webp',
    image_screen :[
      '../assets/images/product/flysurf/dtentes.pompe.electrique-16PSI-B.webp',
      '',
      '',
      '',
      ''
    ],
    price_sell: 0,
    price_promo: 0,
    price_rent_day: 6,
    price_metropole: 0,
    amazon: '',
    description: 'Livré complet avec 5 embouts, 2 tailles de joint, câble allume-cigare :SUP gonflable, kayaks, bateaux, matelas, etc',
    description_long : 'A compléter',
    stars: 5,
    avis_web:"",
    stock: 1,
    poids: 0
  },
  {
    id: 19,
    name: 'Frigo Compression 35L',
    nameRoute: 'Frigo-Compression-euro4*4',
    categorie_tente: false,
    categorie_dtente: true,
    garantie:'',
    periode_essai: '',
    alaUne: false,
    video: 'v48ON5doO0',
    titrevideo:'Frigo à compression Euro4*4',
    image :'../assets/images/product/euro44/dtentes.frigo.compression.webp',
    image_routeur:'../assets/images/product/euro44/dtentes.frigo.compression.webp',
    image_screen :[
      '../assets/images/product/euro44/dtentes.frigo.compression.webp',
      '',
      '',
      '',
      ''
    ],
    price_sell: 0,
    price_promo: 0,
    price_rent_day: 15,
    price_metropole: 0,
    amazon: '',
    description: 'Contenance 35l - Dc 12/24v - Housse incluse - Plage de température -18° à +10° - Prise 220V ou allume cigare.',
    description_long : 'A compléter',
    stars: 5,
    avis_web:"",
    stock: 1,
    poids: 0
  }

]

/* PRODUIT A LA LOCATION */
export interface ProductLocation {
  id: number,
  name: string,
  nameRoute: string,
  caution: string,
  video: string,
  titrevideo:string,
  image: string,
  image_routeur : string,
  image_screen :[
    id1: string,
    id2: string,
    id3: string,
    id4: string,
    id5: string
  ];
  price_rent_day: number,
  price_week_end: number,
  price_VSD: number,
  price_semaine: number,
  price_15j:number,
  price_mois:number,
  price_abonnement:number,
  description: string,
  avis_name:string;
  avis_description:string;
  description_long: string,
  poids: number,
}

export const productsPlage: ProductLocation[] = [
  {
    id: 3,
    name: 'Tente de toit: 3 places',
    nameRoute: 'Tente-de-toit-de-voiture-soft',
    caution:'1750',
    video: '',
    titrevideo:'&#128578;',
    image :'../assets/images/product/tentedetoit/H9074a4ed173f4d8f913b94f4473c445fO.jpg_720x720q50.webp',
    image_routeur:'../assets/images/product/tentedetoit/H9074a4ed173f4d8f913b94f4473c445fO.jpg_720x720q50.webp',
    image_screen :[
      '',
      '',
      '',
      '',
      ''
    ],
    price_rent_day: 25,
    price_week_end: 50,
    price_VSD: 75,
    price_semaine: 160,
    price_15j: 300,
    price_mois:500,
    price_abonnement:0,
    description: 'Tente de L:240 l:145 h/110 -3 places ',
    avis_name: 'client',
    avis_description:'Bien pour dormir à 4 en famille avec ma femme et mes deux anfants en bas âge',
    description_long : '',
    poids: 55
  },
  {
    id: 1,
    name: 'Tente de toit : L=210 l=125 ',
    nameRoute: 'Tente-de-toit-de-voiture-125',
    caution:'2250',
    video: '8LOxFHs21Uc',
    titrevideo:'',
    image :'../assets/images/product/tentedetoit/H7fe85f62303e4ebd80c1c29fc6736256p.jpg_720x720q50.webp',
    image_routeur:'../assets/images/product/tentedetoit/H7fe85f62303e4ebd80c1c29fc6736256p.jpg_720x720q50.webp',
    image_screen :[
      '../assets/images/product/tentedetoit/H7fe85f62303e4ebd80c1c29fc6736256p.jpg_720x720q50.webp',
      '',
      '',
      '',
      ''
    ],
    price_rent_day: 30,
    price_week_end: 60,
    price_VSD: 90,
    price_semaine: 190,
    price_15j: 370,
    price_mois:600,
    price_abonnement:0,
    description: 'Tente de L:210 l:125 2 places',
    avis_name: 'Fred',
    avis_description:'J\'ai du l\'ouvrir à peu près une bonne centaine de fois pour dormir le soir, faire la sieste et regarder le volcan à travers ses 4 fenêtres avec moustiquaire',
    description_long : '<p><b></b</p>',
    poids: 2.4
  },
    {
    id: 2,
    name: 'Tente de toit : L=210 l=140 ',
    nameRoute: 'Tente-de-toit-de-voiture-140',
    caution:'2500',
    video: '8LOxFHs21Uc',
    titrevideo:'',
    image :'../assets/images/product/tentedetoit/H7fe85f62303e4ebd80c1c29fc6736256p.jpg_720x720q50.webp',
    image_routeur:'../assets/images/product/tentedetoit/H7fe85f62303e4ebd80c1c29fc6736256p.jpg_720x720q50.webp',
    image_screen :[
      '../assets/images/product/tentedetoit/H7fe85f62303e4ebd80c1c29fc6736256p.jpg_720x720q50.webp',
      '',
      '',
      '',
      ''
    ],
    price_rent_day: 35,
    price_week_end: 70,
    price_VSD: 99,
    price_semaine: 210,
    price_15j: 400,
    price_mois:700,
    price_abonnement:0,
    description: 'Tente de L:210 l:145 pour 2-3 places',
    avis_name: 'Delphine',
    avis_description:'Après avoir dormi dans cette tente, vous n’aurez plus envie de dormir ailleurs ! Le matelas est un réconfort pour le dos et se détendre, qualité matelassée incroyable ! Avec des ouvertures fenêtres autour, un bel espace au-dessus de la tête, on ne se sent pas enfermé',
   
    description_long : '',
    poids: 75
  },
  {
    id: 2,
    name: 'Tonnelle Apenaz 10 personnes - 9m² ',
    nameRoute: 'Tonnelle-Apenaz-10-personnes-etanches',
    caution:'175',
    video: '',
    titrevideo:'',
    image :'../assets/images/product/decatlon/dtentes-tonelle-apenaz-10-personnes.webp',
    image_routeur:'../assets/images/product/decatlon/dtentes-tonelle-apenaz-10-personnes.webp',
    image_screen :[
      '../assets/images/product/decatlon/dtentes-tonelle-apenaz-10-personnes.webp',
      '',
      '',
      '',
      ''
    ],
    price_rent_day: 0,
    price_week_end: 17,
    price_VSD: 25,
    price_semaine: 40,
    price_15j: 60,
    price_mois:80,
    price_abonnement:0,
    description: 'Tonnelle Etanche 10 personnes',
    avis_name: 'Frederic',
    avis_description:'Dimension : 3m*3m² - 215 hauteur - Pratique lorsque le temps est variable : soleil, pluie .. - Protection solaire',
   
    description_long : '',
    poids: 8
  },
  {
    id: 10,
    name: 'Paddle avec gonfleur',
    nameRoute: 'Paddle-avec-gonfleur',
    caution:'500',
    video: 'OMx3W-0-5dM',
    titrevideo:'&#128578; | Vous fournissons un gonfleur électrique !',
    image :'../assets/images/product/decatlon/dtentes.paddle.webp',
    image_routeur :'../assets/images/product/decatlon/dtentes.paddle.webp',
    image_screen :[
      '',
      '',
      '',
      '',
      ''
    ],
    price_rent_day: 10,
    price_week_end: 20,
    price_VSD: 30,
    price_semaine: 40,
    price_15j: 0,
    price_mois:0,
    price_abonnement:0,
    description: 'Paddle Itiwit avec pagaies et gonfleur électrique.Très stable et facile. Livraison saint pierre - Etang salé : gratuit ; Trou d\'eau : 15 euros)',
    avis_name: 'Fréderic',
    avis_description:'Au lieu de 12 de l\'\heure à l\'\hermitage - Nous vous proposons une solution imbattable',
    description_long : 'A compléter',
    poids: 0
  },
  {
    id: 4,
    name: 'EcoFlow 300 watt',
    nameRoute: 'EcoFlow-RIVER-2-Pro',
    caution:'800',
    video: '',
    titrevideo:'&#128578;',
    image :'../assets/images/product/ecoflow/Ecoflow-delta.webp',
    image_routeur:'../assets/images/product/ecoflow/Ecoflow-delta.webp',
    image_screen :[
      '',
      '',
      '',
      '',
      ''
    ],
    price_rent_day: 10,
    price_week_end: 20,
    price_VSD: 30,
    price_semaine: 50,
    price_15j: 90,
    price_mois:150,
    price_abonnement:0,
    description: 'ECOFLOW 300Watt idéale permet d’alimenter vos appareils habituels où que vous soyez ! Pratique et fiable, elle trouvera facilement une place n’importe où grâce à sa petite taille.',
    avis_name: 'Delphine',
    avis_description:'grâce à cette batterie j\'ai pu recharger téléphone Lumières et faire mon café expresso- Leave no trace',
    description_long : '',
    poids: 55
  },
    {
    id: 4,
    name: 'Frigo Compression 35L',
    nameRoute: 'Frigo-Compression-euro4*4',
    caution:'450',
    video: '-v48ON5doO0',
    titrevideo:'Frigo à compression euro 4*4',
    image :'../assets/images/product/euro44/dtentes.frigo.compression.webp',
    image_routeur:'../assets/images/product/euro44/dtentes.frigo.compression.webp',
    image_screen :[
      '',
      '',
      '',
      '',
      ''
    ],
    price_rent_day: 10,
    price_week_end: 25,
    price_VSD: 30,
    price_semaine: 50,
    price_15j: 75,
    price_mois:100,
    price_abonnement:0,
    description: 'Contenance 35l - Dc 12/24v - Housse incluse - Plage de température -18° à +10° - Prise 220V ou allume cigare.',
    avis_name: 'Delphine et fred',
    avis_description:'Idéal pour avoir de la nourriture maintenue à température durant votre trajet avec le branchement sur l\'allume cigare - Vous pouvez aussi louer la batterie Ecoflow',
    description_long : 'A compléter',
    poids: 15
  }
,
{
  id: 4,
  name: 'Porte Vélo',
  nameRoute: 'Porte-vélo',
  caution:'60',
  video: '',
  titrevideo:'Porte Vélo',
  image :'../assets/images/product/decatlon/porte-velos-hayon-300-2-3-velos.avif',
  image_routeur:'../assets/images/product/decatlon/porte-velos-hayon-300-2-3-velos.avif',
  image_screen :[
    '',
    '',
    '',
    '',
    ''
  ],
  price_rent_day: 10,
  price_week_end: 15,
  price_VSD: 20,
  price_semaine: 30,
  price_15j: 40,
  price_mois:45,
  price_abonnement:0,
  description: 'Porte vélo - Nous demander pour les dimensions',
  avis_name: 'Fred',
  avis_description:'Ne peut porter que des vélos avec cadre assez large',
  description_long : 'A compléter',
  poids: 15
}
,
  {
    id: 5,
    name: 'Tente Qaou V5 pack 3en1 - 2.4 kg',
    nameRoute: 'Tente-Qaou-V5-pack-3en1',
    caution:'180',
    video: 'MaX89pkMqm0',
    titrevideo:'&#128578; | Adventure V5 - 6 en 1',
    image :'../assets/images/product/qaou/tente-v5-Qaou-tente-3-en-1-300x300.webp',
    image_routeur:'../assets/images/product/qaou/tente-v5-qaou-tente-3-en-1-2500x2500.webp',
    image_screen :[
      '',
      '',
      '',
      '',
      ''
    ],
    price_rent_day: 20,
    price_week_end: 22,
    price_VSD: 25,
    price_semaine: 50,
    price_15j: 75,
    price_mois:90,
    price_abonnement:0,
    description: 'Le toit de la tente se transforme en hamac ou en tarp vous pourrez donc moduler l’utilisation de votre Qaou en fonction de vos besoins',
    avis_name:'Fred',
    avis_description:'J\'ai dormi 15 jours avec cette tente entre l\'hermitage et le Maîdo. L\'après-midi j\'installai le hamac !',
    description_long : '<p><b>La Qaou V5 est la dernière version créer par Qaou. Elle bénéficie des 5 années de recherches et développement pour améliorer les performances de nos tentes</b>.<\p><p>Sous tente: Polyamide  et polyester PU 4000 mm<\p><p>Arceaux: Aluminium 8,5 mm<\p><p>1 Double toit modulable: Polyamide 70 D ripstop PU 2000 mm (1 seul double toit / Hamac est fourni dans ce pack)<\p><p>Ce pack vous offre les fonctions suivantes:<\p><p>Tente / Hamac / Abri<\p><p><i>Peut être complété par la suite avec un hamac supplémentaire et un kit de fixation pour avoir l’équivalent d’un pack Adventure. (Tente  / Hamac  / Abri / Tarp)<\i><\p><p>Tente 2 Personnes. Qaou est conçue pour s’adapter à différentes situations, partout où vous irez Qaou s’adaptera !<\p><p>Le toit de la tente se transforme en hamac ou en tarp vous pourrez donc moduler l\’utilisation de votre Qaou en fonction de vos besoins<\p>',
    poids: 2.4
  },
  {
    id: 6,
    name: 'Adventure V5 - 6 en 1 - 3.3kg',
    nameRoute: 'Tente-Qaou-Adventure-V5-pack-6-en-1',
    caution:'240',
    video: 'MaX89pkMqm0',
    titrevideo:'&#128578; | Adventure V5 - 6 en 1',
    image :'../assets/images/product/qaou/adventure-V5- Qaou- Reunion-300x300.webp',
    image_routeur:'../assets/images/product/qaou/adventure-v5-Qaou-reunion-2400-2400.webp',
    image_screen :[
      '',
      '',
      '',
      '',
      ''
    ],
    price_rent_day: 22,
    price_week_end: 24,
    price_VSD: 30,
    price_semaine: 50,
    price_15j: 75,
    price_mois:100,
    price_abonnement:0,
    description: 'Ce pack vous offre les fonctions suivantes: Tente /Tente + auvent / Hamac / Hamac + tarp / Abri / Tarp . Les piquets et l armature en Aluminium No plastique',
    avis_name: 'Frédéric',
    avis_description:'J\'ai dormi 15 jours avec cette tente entre l\'hermitage et le Maîdo. L\'après-midi j\'installai le hamac !',
    description_long : '<b>La Qaou Adventure V5 est la dernière version créer par Qaou. Elle bénéficie des 5 années de recherches et développement pour améliorer les performances de nos tentes.  </b> <p>Sous tente: Polyamide  et polyester PU 4000 mm</p><p>Arceaux: Aluminium 8,5 mm</p><p>Double toit modulable: Polyamide 70 D ripstop PU 2000 mm</p><p>Ce pack vous offre les fonctions suivantes: Tente /Tente + auvent / Hamac / Hamac + tarp / Abri / Tarp</p><p>Tente 2 Personnes. Qaou est conçue pour s adapter à différentes situations, partout où vous irez Qaou s’adaptera !</p><p>Le toit de la tente se transforme en hamac ou en tarp vous pourrez donc moduler l’utilisation de votre Qaou en fonction de vos besoins</p>   <p>2 hamacs sont livrés dans le pack ce qui vous permet de multiple configurations différentes</p>',
    poids: 3.3
  },
  {
    id: 9,
    name: 'Porte-Bebe',
    nameRoute: 'Porte-Bebe',
    caution:'220',
    video: 'SmxIExUyooE',
    titrevideo:'',
    image :'../assets/images/product/decatlon/detentes.porte.bebe.webp',
    image_routeur:'../assets/images/product/decatlon/detentes.porte.bebe.webp',
    image_screen :[
      '',
      '',
      '',
      '',
      ''
    ],
    price_rent_day: 10,
    price_week_end: 15,
    price_VSD: 20,
    price_semaine: 30,
    price_15j: 40,
    price_mois:70,
    price_abonnement:0,
    description: 'Porte Bébé Kit confort plus - Deuter. Pour vos ballades et randos. Poids maximum 18 kg - Pare-soleil, siège ajustable et un dos respirant ',
    avis_name: '',
    avis_description:'',
    description_long : "à compléter",
    poids: 0
  },
    {
    id: 7,
    name: 'Sac-a-dos-homme-55+10L',
    nameRoute: 'Sac-a-dos-homme-55+10L',
    caution:'90',
    video: '',
    titrevideo:'',
    image :'../assets/images/product/intersport/sac-ados-homme-55+10.webp',
    image_routeur:'../assets/images/product/intersport/sac-ados-homme-55+10.webp',
    image_screen :[
      '',
      '',
      '',
      '',
      ''
    ],
    price_rent_day: 6,
    price_week_end: 12,
    price_VSD: 15,
    price_semaine: 30,
    price_15j: 45,
    price_mois:50,
    price_abonnement:0,
    description: ' Conçu pour les randonnées de plusieurs jours, il offre d\'excellentes performances et un confort optimal aux passionnés de voyages. ',
   
    avis_name: '',
    avis_description:'',
    description_long : '<b>',
    poids: 3.3
  },
  {
    id: 8,
    name: 'Sac-a-dos-femme-55+10L',
    nameRoute: 'Sac-a-dos-homme-55+10L',
    caution:'80',
    video: '',
    titrevideo:'',
    image :'../assets/images/product/intersport/sac-ados-femme-55+10.webp',
    image_routeur:'../assets/images/product/intersport/sac-ados-homme-55+10.webp',
    image_screen :[
      '',
      '',
      '',
      '',
      ''
    ],
    price_rent_day: 6,
    price_week_end: 12,
    price_VSD: 15,
    price_semaine: 30,
    price_15j: 40,
    price_mois:50,
    price_abonnement:0,
    description: ' Conçu pour les randonnées de plusieurs jours, il offre d\'excellentes performances et un confort optimal aux passionnés de voyages. ',
    avis_name: '',
    avis_description:'',
    description_long : '<b>',
    poids: 3.3
  },
  {
    id: 11,
    name: 'Pompe électrique-16psiA',
    nameRoute: 'Pompe électrique-16psiA',
    caution:'80',
    video: '',
    titrevideo:'',
    image :'../assets/images/product/flysurf/dtentes.pompe.electrique-16PSI-B.webp',
    image_routeur:'../assets/images/product/flysurf/dtentes.pompe.electrique-16PSI-B.webp',
    image_screen :[
      '',
      '',
      '',
      '',
      ''
    ],
    price_rent_day: 10,
    price_week_end: 10,
    price_VSD: 10,
    price_semaine: 30,
    price_15j: 40,
    price_mois:50,
    price_abonnement:0,
    description: 'Livré complet avec 5 embouts, 2 tailles de joint, câble allume-cigare :SUP gonflable, kayaks, bateaux, matelas, etc',
    avis_name: '',
    avis_description:'',
    description_long : "Livré avec deux joints de taille différents pour les SUP gonflable, il ne faut pas hésiter à en retirer un et à alterner pour trouver celui qui s'adapte parfaitement !",
    poids: 2
  },
  {
    id: 12,
    name: 'Pompe électrique-16psiB',
    nameRoute: 'Pompe électrique-16psiB',
    caution:'80',
    video: '',
    titrevideo:'',
    image :'../assets/images/product/flysurf/dtentes.pompe.electrique-16PSI-A.webp',
    image_routeur:'../assets/images/product/flysurf/dtentes.pompe.electrique-16PSI-A.webp',
    image_screen :[
      '',
      '',
      '',
      '',
      ''
    ],
    price_rent_day: 10,
    price_week_end: 10,
    price_VSD: 10,
    price_semaine: 30,
    price_15j: 40,
    price_mois:50,
    price_abonnement:0,
    description: 'Livré complet avec 5 embouts, 2 tailles de joint, câble allume-cigare :SUP gonflable, kayaks, bateaux, matelas, etc',
    avis_name: '',
    avis_description:'',
    description_long : 'A compléter',
    poids: 0
  },
  
];

